apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../helm_base

namespace: secrets-store-csi-driver-provider-aws

commonLabels:
  # app.kubernetes.io/app: secrets-store-csi-driver-provider-aws
  app.kubernetes.io/managed-by: argocd

resources:
  - namespace.yml
