apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-store-csi-driver
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: secrets-store-csi-driver
    name: in-cluster
  project: core-services-project
  source:
    path: kubernetes/mo/kustomized-helm-charts/secrets-store-csi-driver/kustomize/overlays
    repoURL: https://github.com/brevanhowardinfra/tf-aws-bh-eks-core-infra
    targetRevision: HEAD
    plugin:
      name: kustomized-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
